### ISSUE TITLE
Error when attempting to create Azure DevTestLab Create VM function: Get-AzureDtlLab

### ISSUE THREAD

**Issue by lorrinferdinand** [Azure/azure-devtestlab#201]
Validating input parameters
2017-03-02T17:23:09.3715367Z 
2017-03-02T17:23:09.3715367Z 
2017-03-02T17:23:09.5287467Z Fetching lab 'XXXXXXXXX'
2017-03-02T17:23:09.5287467Z 
2017-03-02T17:23:09.5287467Z 
2017-03-02T17:23:10.0121846Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 
2017-03-02T17:23:10.0121846Z The term 'Get-AzureRmResource' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2017-03-02T17:23:10.0121846Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-03-02T17:23:10.0121846Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-03-02T17:23:10.0121846Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-03-02T17:23:10.0121846Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-03-02T17:23:10.0121846Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-03-02T17:23:10.0121846Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2017-03-02T17:23:10.0434371Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2017-03-02T17:23:10.0434371Z 

Any ideas?  
The error is occuring in Get-AzureDtlLab when it calls Get-AzureRmResource.

Is this a dataissue - we are passing the wrong LabId?

Thanks for any help with this....?

**Comment by leovms** [comment]
_The term `Get-AzureRmResource` is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._

The message indicates the Azure PS SDK is probably not properly installed and/or the paths don’t reflect properly on where these commands are located. Can you recommend customer to install using the **msi installer** of the [latest Azure SDK](https://github.com/Azure/azure-powershell/releases) and give a try.
