### ISSUE TITLE
VSTS Deployment Group - Fails to apply artifact on DTL VM creation

### ISSUE THREAD

**Issue by smdonoghue** [Azure/azure-devtestlab#275]
When attempting to create a VM within DevTest Labs - pre-conifgured to apply the VSTS Deployment group artifact, we're getting a failure message. However, if I was to create the VM and apply the artifact afterwards manually, it would be installed correctly. Do you know why this would be?

Also, if the first issue above is able to be resolved, then how would we go about supplying the correct access token to the artifact during the release process (VM creation) as I believe the access token to refresh after a certain period of time. Does this make sense?

Thanks.

**Comment by leovms** [comment]
Can you provide the "failure message"?

Can you clarify what you mean when you say "release process"? Are you referring to using VSTS and Release Management? Are you referring to passing parameters from a VSTS task? Can you clarify?

**Comment by SMDonoghue** [comment]
I've tried again today and the extension seems to be installing fine so that is potentially no longer an issue.

Yes, we are using VSTS for the build and release process. As part of the release tasks we currently create a DTL virtual machine based on a custom image with the VSTS Deployment Group agent already installed. 

What we ideally want is to be able to add the agent to the VM at the time of creation to eliminate the need for a custom image. In order to do this I'm guessing we would need to create an ARM template for the VM that includes the "VSTS Deployment Group" artifact and take in the relevant parameters such as URL, project name, deployment group name and access token. It's specifying the access token that seems to be the part I'm struggling with - as in how do we retrieve this during the release tasks to pass to the new DTL virtual machine?

**Comment by leovms** [comment]
Got it. Yes, you would create the ARM template from DTL via the **View arm template** command in the New VM blade.

The way to pass the PAT is by creating a [secret variable](https://www.visualstudio.com/en-us/docs/build/define/variables#user-defined-variables) in your build/release definition. This will ensure your PAT is protected. You then pass it in the **Template Parameters**.

For example, say you create a secret variable called **MyPAT**, you would pass its value as **'$(MyPAT)'**.

Note that the build/release agent will honor such secret variables and ensure they are passed safely to your script.

**Comment by smdonoghue** [comment]
Thanks for getting back.

I'm receiving the error again now - please see the attached...

It appears as though I'm being returned a login page so I'm assuming my PAT isn't being passed into the VM creation correctly. Do you agree?

![image](https://user-images.githubusercontent.com/2563987/29572653-d27ac46a-8754-11e7-8c6d-8969e31ab7aa.png)

**Comment by smdonoghue** [comment]
Also, if I attempt to override the "VSTS_Deployment_group_agent.PersonalAccessToken" parameter within our "Create Web Server" release task we receive the following error whilst running...

2017-08-22T15:11:47.7526130Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 
2017-08-22T15:11:47.7526130Z 3:11:47 PM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The template parameters 'String' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'newVMName, labName, size, userName, password, VSTS_Deployment_group_agent.accountUrl, VSTS_Deployment_group_agent.projectName, VSTS_Deployment_group_agent.deploymentGroupName, VSTS_Deployment_group_agent.PersonalAccessToken, VSTS_Deployment_group_agent.deploymentAgentTags, VSTS_Deployment_group_agent.agentInstallPath, VSTS_Deployment_group_agent.agentName'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.
2017-08-22T15:11:47.7526130Z 
2017-08-22T15:11:47.7526130Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-08-22T15:11:47.7536128Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-08-22T15:11:47.7536128Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-08-22T15:11:47.7536128Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-08-22T15:11:47.7536128Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-08-22T15:11:47.7536128Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2017-08-22T15:11:47.7676152Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2017-08-22T15:11:47.7686146Z ##[section]Finishing: Create Web Server

**Comment by leovms** [comment]
Try using the parameter `-TemplateParameterObject` in your call to `New-AzureRmResourceGroupDeployment`, as in the following example. Pay attention to how `"Test_Parameter_Types.selectParam"` is defined.

``` PS
[CmdletBinding()]
Param(
    $SubscriptionId = '<SubId>'
    $ResourceGroupName = '<RgName>',
    $VmName = '<VmName>'
)

try
{
    pushd $PSScriptRoot

    Select-AzureRmSubscription -SubscriptionId $SubscriptionId | Out-Null

    $templateFile = Resolve-Path './templates/dtl-arm-template.json'
    $templateParams = @{
        newVMName = $VmName
        "Test_Parameter_Types.selectParam" = 'test2'
    }
    New-AzureRmResourceGroupDeployment -Name "Dtl$((New-Guid).ToString())" -ResourceGroupName $ResourceGroupName -TemplateFile "$TemplateFile" -TemplateParameterObject $templateParams
}
finally
{
    1..3 | % { [console]::beep(2500,300) } # Make a sound to indicate we're done.
    popd
}
```

**Comment by leovms** [comment]
The problem is the period. Try removing the period from the one parameter you are passing from the task.

**Comment by smdonoghue** [comment]
Thanks @leovms - renaming the parameter within the ARM template and also the input template parameter worked!

Perhaps the parameters should be renamed by default so that nobody falls into the same issues that I was having or is there another reason they are named this way?

**Comment by leovms** [comment]
Not sure, TBH. I think this is the convention used by ARM for child resources. I'm glad you're unblocked.
