### ISSUE TITLE
Cannot access artifacts

### ISSUE THREAD

**Issue by LukeRH** [Azure/azure-devtestlab#428]
Hi,
I can no longer access artifacts which are part of a formula via the portal it just hangs loading, i get the following error in the console.
KWFZ6h_2XSME.js:8 [Microsoft_Azure_DevTestLab]  08:43:51 MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Cannot read property 'id' of null
stack: TypeError: Cannot read property 'id' of null
    at new n (https://afd.hosting.portal.azure.net/devtestlab/Content/Dynamic/bx5UKzd2f9FQ.js:2:583)
    at https://afd.hosting.portal.azure.net/devtestlab/Content/Dynamic/ZGygF-9gLh5d.js:1:1474
    at o (https://portal.azure.com/Content/Dynamic/JayIFb5qHGFZ.js:4:72)
    at https://portal.azure.com/Content/Dynamic/JayIFb5qHGFZ.js:4:5156

Please can you help

Thanks
Luke

**Comment by slime-uk** [comment]
I can see our formula and it says 13 artifacts but I can't edit them.  When I try and create a VM based on a formula, our formula is shown containing 0 artifacts at the bottom of the new VM GUI page.  I didn't try and actually create a VM as there is no point with 0 artifacts.

**Comment by tanmayeekamath** [comment]
Was this issue resolved for you?

**Comment by slime-uk** [comment]
Yes - fixed after about a month of the service outage. What is still not fixed is artefact progress showing no output at times. Seems to be a screen/browser refresh issue and is random. When we fire up a formula with say 13 artefact steps somewhere during the run it stops reporting any sort of output in the right hand blade even though the list on the left can say success the right hand output for many of the artefacts is blank and even the started and other status entries are wrong. This is random but really annoying. Any comment please?

**Comment by tanmayeekamath** [comment]
This issue should be resolved now. Please reopen if you are still experiencing the issue.

**Comment by code-srg** [comment]
I am getting this issue  from yesterday, can you please help

12:53:26 PM MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: message: Cannot read properties of undefined (reading 'id')
name: TypeError
stack: TypeError: Cannot read properties of undefined (reading 'id')
    at t.<anonymous> (https://portal.azure.com/Content/Dynamic/bGBqsqJLjS0f.js:4:5834)
    at s (https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:17:2634)
    at Object.next (https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:17:1927)
    at https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:17:1850
    at new Promise (<anonymous>)
    at __awaiter (https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:17:1644)
    at t.onProcessRequest (https://portal.azure.com/Content/Dynamic/bGBqsqJLjS0f.js:4:5552)
    at Array.steps (https://portal.azure.com/Content/Dynamic/PWnAx4GqlSUU.js:153:3590)
    at https://portal.azure.com/Content/Dynamic/PWnAx4GqlSUU.js:153:1451
    at s (https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:17:2634)
    at Object.next (https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:17:1927)
    at o (https://portal.azure.com/Content/Dynamic/-mPDykxZ7mlI.js:17:1700)

**Comment by micro-dev** [comment]
I am also seeing this error
