### ISSUE TITLE
Create Environment failing on Get-Member cmdlet

### ISSUE THREAD

**Issue by InsaneNL** [Azure/azure-devtestlab#486]
Creating a environment from a ARM template using the Create environment task fails on a Get-Member cmdlet somwhere in the task, i have not yet been able to test the other tasks. It seems to happen with every Template i try, i have been testing with some custom templates (https://github.com/InsaneNL/azurearmtemplate) and the quickstart templates (https://github.com/Azure/azure-quickstart-templates). 

AzurePSCmdletsVersion= 6.13.1
PSVersion = 5.1.17763.316

019-05-13T06:48:06.1464466Z Parameters = [not displayed for security reasons]
2019-05-13T06:48:06.1476956Z TemplateOutputVariables = false
2019-05-13T06:48:06.1809797Z Creating Environment with parameters
2019-05-13T06:48:08.5007368Z Completing Azure DevTest Labs Create Environment Task
2019-05-13T06:48:08.5285322Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 
2019-05-13T06:48:08.5295534Z You must specify an object for the Get-Member cmdlet.
2019-05-13T06:48:08.5295951Z at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2019-05-13T06:48:08.5296381Z at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2019-05-13T06:48:08.5296905Z at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2019-05-13T06:48:08.5297478Z at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-05-13T06:48:08.5298126Z at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-05-13T06:48:08.5298732Z at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2019-05-13T06:48:08.5660169Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by leovms** [comment]
@InsaneNL, thank you for reporting the issue. Give me some time to repro and get back to you.

**Comment by leovms** [comment]
I have validated the task with the latest Azure PS (i.e. Azure v5.3.0 and AzureRM v6.13.1) and all seems good. I am therefore not able to repro what you reported.

I will close this issue, but feel free to re-open it. If you do, please provide me a sample environment and include the parameters you use. I need to have as many details as possible to repro the case; otherwise, I will not be able to help.

**Comment by InsaneNL** [comment]
sorry, i didn't see the edit to your first comment, i tried that now with the WebApp template from the public environment repo and it fails as well on the same "you must specify an object for the Get-Member cmdlet" error. We run TFS 2018(16.131.27701.1) and the build server is a fresh Windows Server 2019 installation with PowerShell 5.1.17763.316, the TFS agent, Azure v5.3.0, AzureRM v6.13.1 and Google Chrome installed. Is there anything I could be missing that may cause this?

**Comment by leovms** [comment]
@InsaneNL, reach out to me via email (leov at microsoft dot com). Let's set up time to look at this together.
